homeaway/datapull

- api/pom.xml
- core/pom.xml
- functional-test/pom.xml
Fix Security Issues Flaged by Github
POM files of API ,Core and functional tests
> Dt 1468 core

- README.md
- core/pom.xml
_&lt;High level description of the PR&gt;_
* _&lt;detail item of what was added&gt;_
* _&lt;describe functionality added&gt;_
* _&lt;detail item of what was changed&gt;_
* _&lt;describe functionality that was changed&gt;
* _&lt;in particular, describe BACKWARD INCOMPATIBLE changes&gt;
* _&lt;detail item of what was removed&gt;_
> Adding the commons config dependency

- CHANGELOG.md
- api/src/main/resources/terraform/datapull_iam/create_user_and_roles.sh
- core/src/main/scala/core/DataPull.scala
Bug Fix
* Fixed bug - "No JSON input available to Data Pull" exception
> "No json input available to Data Pull" bug fix

- core/src/main/scala/core/DataFrameFromTo.scala
- core/src/main/scala/core/DataPull.scala
- core/src/main/scala/core/Migration.scala
- core/src/main/scala/logging/DataPullLog.scala
we support writing as any regular formats such as jsons, parquet, avro, csv etc from a dataframe which is different from what we need.
* NA
* core/src/main/scala/core/DataFrameFromTo.scala
* core/src/main/scala/core/DataPull.scala
* core/src/main/scala/core/Migration.scala
* core/src/main/scala/logging/DataPullLog.scala
* NA
> Adding functionality to write json strings to a file system.

- core/src/main/scala/core/Migration.scala
Auto deleting temp s3 files which are created as part of storing temp files while reading data from kafka or mongodb
N/A
* core/src/main/scala/core/Migration.scala
NA
> Adding functionality auto delete the tmp s3 files

- core/pom.xml
- core/src/main/scala/core/Migration.scala
This is to fix the bug while retrieving the secrets from the secretsmanager.
* NA
* core/pom.xml
* core/src/main/scala/core/Migration.scala
* NA
> Secret manager debug

- CHANGELOG.md
- core/src/main/scala/core/DataFrameFromTo.scala
Bug Fix:-
java.lang.ClassCastException: java.lang.String cannot be cast to com.mongodb.MongoClientURI
Instead of asInstanceOf[MongoClientURI] we are using the new object of MongoClientURI.
asInstanceOf[MongoClientURI]
> MongoURIFix

- CHANGELOG.md
- core/pom.xml
- Update jettison dependency
- core/pom.xml
-
> add dependency

- CHANGELOG.md
- core/src/main/scala/core/DataPull.scala
- Fixed a bug which was mandating aws secret access key for every migration
- core/src/main/scala/core/DataPull.scala
> adding to CHANGELOG.md

- CHANGELOG.md
- core/src/main/resources/Samples/Input_Json_Specification.json
- core/src/main/scala/core/DataPull.scala
- core/src/main/scala/core/Migration.scala
This is to accept additional spark conf from the user for any migration 
- core/src/main/scala/core/Migration.scala
- core/src/main/scala/core/DataPull.scala
> Bug fix coalexce file count type casting

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
- api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
- api/src/main/resources/application-dev.yml
- api/src/main/resources/application-prod.yml
- api/src/main/resources/application-stage.yml
- api/src/main/resources/application-test.yml
- core/src/main/resources/Samples/Input_Json_Specification.json
- master_application_config-dev.yml
- master_application_config-prod.yml
- master_application_config-stage.yml
- master_application_config-test.yml
Added fields of hive_properties to input json. These properties are passed to the RunJobFlowRequest to spin up Spark EMR cluster with Hive configurations.
* Properties in EMRProperties.java and ClusterProperties.java for Hive configurations
* Hive as application to RunJobFlowRequest with configurations
* Yaml files to have fields related to Hive config
> Hive support

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
Added optional ClusterProperties to allow users to define spark-defaults and spark-metrics EMR configurations.
> Spark defaults and metrics classification

- CHANGELOG.md
- core/src/main/scala/core/Controller.scala
- core/src/main/scala/core/DataPull.scala
Same email fix, just adding to CHANGELOG
> Failure email fix

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
- core/src/main/resources/Samples/Input_Json_Specification.json
Added functionally to configure hdfs-site.xml from the Input JSON.
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
- api/src/main/java/com/homeaway/datapullclient/input/ClusterProperties.java
> Datapull- Adding functionality to add hdfs-site  params from the input json 

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
Fixed bug of a missing bracket in the datapulltask file.
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
> Hdfs bug fix

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
Fixed bug for datapull subnet-id's issue (picking all default id's randomly)
> Distributing the EMR job submission to all the subnets

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
We have modified the code for providing precedence to user tag over the default tags while EMR cluster creation.
api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
> Usertag precedence

- CHANGELOG.md
- core/pom.xml
- core/src/main/resources/Samples/Input_Json_Specification.json
- core/src/main/scala/core/DataFrameFromTo.scala
- core/src/main/scala/core/Migration.scala
This is to add a feature for users to give the partition columns while writing to a hive table.
- core/src/main/resources/Samples/Input_Json_Specification.json
- core/src/main/scala/core/DataPull.scala
- core/src/main/scala/core/Migration.scala
> Adding the functionality to enable writing to a partitioned hive table.

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
- core/src/main/resources/Samples/Input_Json_Specification.json
Adding the functionality to able the users to ssh into the ec2 boxes
api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
> Adding the functionality to able the users to ssh into the ec2 boxes

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
- core/src/main/scala/core/DataFrameFromTo.scala
Issue with the empty/null subnetId
*  Added  empty or null check
* Added StringUtils.isNotBlank(dataPullProperties.getApplicationSubnet3())
*   DataPullTask file was modified 
*  Added StringUtils.isNotBlank(dataPullProperties.getApplicationSubnet3())
- [ X] CHANGELOG.md updated
- [ X] Reviewer assigned
> EGDM-4575 - Issue related to Datapull API jobs 

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/config/DataPullClientConfig.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullRequestProcessor.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
Added code to rotate subnet for each api submit request to run DataPull
> Modified code to rotate subnet support

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/api/DataPullClientApi.java
- api/src/main/java/com/homeaway/datapullclient/config/DataPullClientConfig.java
- api/src/main/java/com/homeaway/datapullclient/data/ClusterStepCollection.java
- api/src/main/java/com/homeaway/datapullclient/data/JobStatus.java
- api/src/main/java/com/homeaway/datapullclient/handlers/DataPullRequestHandler.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullRequestProcessor.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
- api/src/main/java/com/homeaway/datapullclient/service/DataPullClientService.java
- api/terraform/datapull_task/ecs_deploy.sh
Changes Added to support job Status and cluster termination api
ClusterStepCollection class is added
JobStatus  class is added
New Api for JobStatus and terminate cluster added
DataPullClient API updated
DataPullTask
DataPullClientService
DataPullRequestHandler
DataPullRequestProcessor
> Changes Added to support job Status and cluster termination api

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
Modified code to pick only the first subnet ID from the subnet-list and mandated EMR version to 5.36.2
-DatapullTask.java,EMRProperties.java
> Subnet mapping and EMR version update

- CHANGELOG.md
- core/src/main/resources/Samples/Input_Json_Specification.json
- core/src/main/scala/core/DataFrameFromTo.scala
- core/src/main/scala/core/Migration.scala
- core/src/main/scala/helper/Helper.scala
- manual-tests/mssql_dataset_to_mysql_to_mssql/datapull_input.json
Taking the URI from the user for all the RDBMS
-DataFrameFromTo.scala
> update database url

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
Upgrading the emr label to fix some vulnerabilities.
-api/src/main/java/com/homeaway/datapullclient/config/EMRProperties.java
> Upgrading the emr label to fix some vulnerabilities.

- CHANGELOG.md
- core/src/main/scala/core/DataFrameFromTo.scala
_&lt;java.util.NoSuchElementException: key not found: url&gt;_
* _&lt;core/src/main/scala/core/DataFrameFromTo.scala&gt;_
* _&lt;configMap.getOrElse("url", "")&gt;
* _&lt;yes&gt;
> fix java.util.NoSuchElementException: key not found

- CHANGELOG.md
- api/src/main/java/com/homeaway/datapullclient/process/DataPullRequestProcessor.java
- api/src/main/java/com/homeaway/datapullclient/process/DataPullTask.java
Addressing listCluster concurrency issue by changing HashMap to ConcurrentHashMap 
api/src/main/java/com/homeaway/datapullclient/process/DataPullRequestProcessor.java
api/src/main/java/com/homeaway/datapullclient/data/ClusterStepCollection.java
> New listcluster concurrency issue
